- hosts: localhost
  connection: local
  gather_facts: yes
  sudo: no
  vars:
    homebrew_cask_packages_packages:
    - calibre
    - firefox
    - google-chrome
    - google-japanese-ime
    - grandperspective
    - iterm2
    - vagrant
    - virtualbox
    - xquartz
    - webstorm
    homebrew_packages:
    - tmux
    - zsh
    - peco
    - antigen
    - fish
    - gawk
    - ghq
    - go
    - python
    - py
    - z
    - tree
    - hub
    - nodebrew

  roles:
  - role: hnakamur.homebrew_packages
    tags: homebrew_packages
  - role: hnakamur.homebrew_cask_packages
    tags: homebrew_cask_packages
